ALTER TABLE public.conversation_logs ALTER COLUMN session_id TYPE uuid USING session_id::uuid;
ALTER TABLE public.course_feedback ALTER COLUMN student_id TYPE uuid USING student_id::uuid;
ALTER TABLE public.quiz_results ALTER COLUMN student_id TYPE uuid USING student_id::uuid;
ALTER TABLE public.student_sessions ALTER COLUMN id TYPE uuid USING id::uuid;
ALTER TABLE public.student_sessions ALTER COLUMN id DROP IDENTITY;
ALTER TABLE public.student_sessions ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.course_feedback ADD CONSTRAINT course_feedback_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
CREATE POLICY "Allow public insert" ON public.course_feedback FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public read" ON public.course_feedback FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE public.lesson_progress (id uuid DEFAULT gen_random_uuid() NOT NULL, session_id uuid NOT NULL, lesson_id uuid NOT NULL, is_unlocked boolean DEFAULT false NOT NULL, is_current boolean DEFAULT false NOT NULL, completed_at timestamp with time zone, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.lesson_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_progress ADD CONSTRAINT lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_progress ADD CONSTRAINT lesson_progress_pkey PRIMARY KEY (id);
ALTER TABLE public.lesson_progress ADD CONSTRAINT lesson_progress_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.student_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_progress ADD CONSTRAINT lesson_progress_session_id_lesson_id_key UNIQUE (session_id, lesson_id);
GRANT ALL ON public.lesson_progress TO anon;
GRANT ALL ON public.lesson_progress TO authenticated;
GRANT ALL ON public.lesson_progress TO service_role;
CREATE POLICY "profiles insert own" ON public.profiles FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = id));
CREATE POLICY "profiles read own" ON public.profiles FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = id));
CREATE POLICY "profiles update own" ON public.profiles FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = id)) WITH CHECK ((( SELECT auth.uid() AS uid) = id));
CREATE POLICY "public can read profiles" ON public.profiles FOR SELECT TO anon, authenticated USING (true);
ALTER TABLE public.quiz_results ADD CONSTRAINT quiz_results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.student_sessions ADD COLUMN vl_session_key text;
ALTER TABLE public.student_sessions ADD COLUMN current_lesson_id uuid;
ALTER TABLE public.student_sessions ADD CONSTRAINT student_sessions_current_lesson_id_fkey FOREIGN KEY (current_lesson_id) REFERENCES public.lessons(id) ON DELETE SET NULL;
CREATE POLICY "Users can insert their own sessions" ON public.student_sessions FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = student_id));
