ALTER TABLE public.enrollments DROP COLUMN class_code;
ALTER TABLE public.enrollments DROP COLUMN name;
ALTER TABLE public.quiz_results DROP COLUMN class_code;
ALTER TABLE public.quiz_results DROP COLUMN name;
ALTER TABLE public.student_sessions DROP COLUMN class_code;
ALTER TABLE public.student_sessions DROP COLUMN name;
ALTER TABLE public.enrollments ADD COLUMN student_id uuid;
ALTER TABLE public.enrollments ADD CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id);
ALTER TABLE public.enrollments ADD COLUMN class_id uuid;
ALTER TABLE public.enrollments ADD CONSTRAINT enrollments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id);
ALTER TABLE public.lesson_materials ADD COLUMN lesson_id uuid;
ALTER TABLE public.lesson_materials ADD CONSTRAINT lesson_materials_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);
ALTER TABLE public.lesson_materials ADD COLUMN file_url text;
ALTER TABLE public.lessons ADD COLUMN class_id uuid;
ALTER TABLE public.lessons ADD CONSTRAINT lessons_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id);
ALTER TABLE public.profiles ADD COLUMN student_code text;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_student_id_key UNIQUE (student_code);
ALTER TABLE public.quiz_results ADD COLUMN student_id uuid;
ALTER TABLE public.quiz_results ADD CONSTRAINT quiz_results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id);
ALTER TABLE public.quiz_results ADD COLUMN lesson_id uuid;
ALTER TABLE public.quiz_results ADD CONSTRAINT quiz_results_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id);
ALTER TABLE public.student_sessions ADD COLUMN student_id uuid;
ALTER TABLE public.student_sessions ADD CONSTRAINT student_sessions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id);
ALTER TABLE public.student_sessions ADD COLUMN class_id uuid;
ALTER TABLE public.student_sessions ADD CONSTRAINT student_sessions_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id);
